language: python
python:
  - '3.5'
cache: pip
install:
  - pip install -r requirements.txt
  - wget https://github.com/samtools/bcftools/releases/download/1.6/bcftools-1.6.tar.bz2
  - tar xf /home/bcftools-1.6.tar.bz2
  - cd /home/bcftools && ./configure --prefix /usr && make && sudo make install
script:
  - python tests.py