language: python
python:
  - '3.5'
cache: pip
install:
  - pip install -r requirements.txt

before_script:
  - wget https://github.com/samtools/bcftools/releases/download/1.6/bcftools-1.6.tar.bz2 -O /home/bcftools.tar.bz2
  - tar xf /home/bcftools.tar.bz2
  - cd /home/bcftools && ./configure --prefix /home && make && make install
script:
  - python tests.py